Repository udistrital/terceros_crud, pull requests merged in 2019-11, with the labels that each got.

#9 Dev
  .drone.yml
Labels: enhancement

#10 Se corrijen fechas de migrate #4
  .drone.yml
  database/migrations/20191025_115660_crear_schema.go
  database/migrations/20191025_115661_crear_tabla_tipo_documento.go
  database/migrations/20191025_115662_crear_tabla_tipo_contribuyente.go
Labels: enhancement

#11 Se corrijen fechas de migrate #4
  database/migrations/20191025_115700_crear_schema.go
  database/migrations/20191025_115701_crear_tabla_tipo_documento.go
  database/migrations/20191025_115702_crear_tabla_tipo_contribuyente.go
Labels: bug

#12 Se corrijen fechas de migrate #4
  database/migrations/20191025_115705_crear_tabla_tipo_documento.go
  database/migrations/20191025_115710_crear_tabla_tipo_contribuyente.go
  database/migrations/20191025_115951_crear_tabla_grupo_info_complementaria.go
  database/migrations/20191025_120313_crear_tabla_info_complementaria.go
  database/migrations/20191025_120726_crear_tabla_tipo_tercero.go
Labels: bug

#13 Se corrijen fechas de migrate #4
  database/migrations/20191025_120320_crear_tabla_grupo_info_complementaria.go
  database/migrations/20191025_120325_crear_tabla_info_complementaria.go
Labels: bug

#14 Re despliegue #4
  main.go
Labels: enhancement

#15 Update README.md
  README.md
Labels: documentation

#17 Se agrega usuario de WSO2 a peticion de Jhon y equipo de acade…
  database/migrations/20191119_144700_alter_table_terceros_add_usuario_wso2.go
  models/tercero.go
  sql/Terceros_Schema.png
  sql/Terceros_Schema.sql
Labels: enhancement

#18 Se agregan archivos de Migra…
  database/migrations/20191125_142715_insert_tabla_tipo_contribuyente.go
  database/migrations/20191125_142900_insert_tabla_tipo_tercero.go
  database/migrations/20191125_153241_insert_tabla_grupo_info_complementaria.go
  database/migrations/20191125_153402_insert_tabla_info_complementaria.go
  sql/grupos_info_complementaria.sql
Labels: enhancement

#21 Con @mariaalejandra9404 se agregan archivos de migra…
  database/migrations/20191128_113756_insert_tabla_grupo_info_complementaria.go
  database/migrations/20191128_113810_insert_tabla_terceros_relacionadas_data_bancos.go
  sql/grupos_info_complementaria.sql
Labels: enhancement

#22 Se modifica archivo de migracion
  database/migrations/20191128_113810_insert_tabla_terceros_relacionadas_data_bancos.go
Labels: enhancement

#23 Se modifica archivo de migracion
  database/migrations/20191128_113810_insert_tabla_terceros_relacionadas_data_bancos.go
Labels: bug

#24 Se agrega info complementaria persona que costea los estudios
  database/migrations/20191128_152420_info_complementaria.go
  sql/grupos_info_complementaria.sql
Labels: enhancement
